FROM ruby:2.6.4

# パッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential \
                        libpq-dev \
                        nodejs \
    && rm -rf /var/lib/apt/lists/*

# install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update
RUN apt-get install -y yarn

# コンテナのディレクトリ設定
ENV APP_ROOT /app

RUN mkdir ${APP_ROOT}

WORKDIR ${APP_ROOT}

ADD Gemfile ${APP_ROOT}/Gemfile
ADD Gemfile.lock ${APP_ROOT}/Gemfile.lock
RUN bundle install

RUN mkdir -p tmp/pids
RUN mkdir -p tmp/sockets

# yarn install
RUN yarn install
RUN yarn add bootstrap-material-design
RUN yarn install

ADD . ${APP_ROOT}
RUN cp -v config/database.ci.yml config/database.yml

RUN yarn add bootstrap-material-design
RUN yarn install

# puma起動
# CMD bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"