version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: diary_app_development
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "6989"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
      image: redis:6.2
      ports:
        - 6379:6379
      volumes:
        - ./data/redis:/data
      environment:
        REDIS_URL: redis://redis:6379
      command: redis-server --appendonly yes
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # pry-byebugを使えるようにする
    tty: true
    stdin_open: true
    depends_on:
      - db #DBコンテナ起動後に実行
    ports:
      - 3000:3000
    volumes:
      - .:/app
volumes:
  mysql-data: