version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - test-db
    ports:
      - 3000:3000
  web:
    build:
      context: containers/nginx
    ports:
      - 80:80
    depends_on:
      - app
  test-db:
    image: mysql:5.7
    ports:
      - 4306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: '%'
  redis:
      image: redis:6.2
      ports:
        - 6379:6379
      environment:
        REDIS_URL: redis://redis:6380
      command: redis-server --appendonly yes
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
    logging:
      driver: none