version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
  web:
    build: 
      context: containers/nginx
      dockerfile: Dockerfile.prod
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    # depends_on:
    #   - app
  redis:
      image: redis:6.2
      ports:
        - 6379:6379
      volumes:
        - ./data/redis:/data
      environment:
        REDIS_URL: redis://redis:6379
      command: redis-server --appendonly yes
volumes:
  public-data:
  tmp-data:
  log-data: