version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.test
    tty: true # pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - test-db
  test-db:
    image: mysql:5.7
    # ports:
    #   - 4306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: diary_app_test
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "6989"
  redis:
      image: redis:6.2
      environment:
        REDIS_URL: redis://redis:6380
      command: redis-server --appendonly yes
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none