version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true # pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - db #DBコンテナ起動後に実行
    ports:
      - 3000:3000
    volumes:
      - .:/app:delegated #delegatedで同期の一貫性を保証しないでパフォーマンス向上
  db:
    image: mysql:5.7
    ports:
      - 4306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: diary_app_development
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "6989"
    volumes:
      - mysql-data:/var/lib/mysql:delegated #delegatedで同期の一貫性を保証しないでパフォーマンス向上
  test-db:
    image: mysql:5.7
    ports:
      - 4307:3307 #開発のポート番号と別にする
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: diary_app_test
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "6989"
      #データの永続化なし
  redis:
      image: redis:6.2
      ports:
        - 6379:6379
      volumes:
        - ./data/redis:/data:delegated #delegatedで同期の一貫性を保証しないでパフォーマンス向上
      environment:
        REDIS_URL: redis://redis:6379
      command: redis-server --appendonly yes
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
volumes:
  mysql-data: