FROM ruby:2.6.4

# パッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential \
                        libpq-dev \
                        nodejs \
    && rm -rf /var/lib/apt/lists/*

# yarnのインストール
RUN curl https://deb.nodesource.com/setup_12.x | bash \
    curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    apt-get update && apt-get install -y nodejs yarn postgresql-client

# コンテナのディレクトリ設定
ENV APP_ROOT /app

WORKDIR $APP_ROOT

ADD Gemfile ${APP_ROOT}/Gemfile
ADD Gemfile.lock ${APP_ROOT}/Gemfile.lock

RUN bundle install

COPY . $APP_ROOT
RUN cp -v config/database.ci.yml config/database.yml