version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.test
    tty: true # pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - test-db
      - redis
      - selenium_chrome
  test-db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: diary_app_test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: "6989"
  redis:
      image: redis:6.2
      ports:
        - 6379:6379
      environment:
        REDIS_URL: redis://redis:6379
      command: redis-server --appendonly yes
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none