version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    # dependencies:
    #   pre:
    #     - |
    #       if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
    #         echo "Download and install Yarn."
    #         curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    #       else
    #         echo "The correct version of Yarn is already installed."
    #       fi
    #   override:
    #     - yarn install
    #   cache_directories:
    #     - ~/.yarn
    #     - ~/.cache/yarn
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose -f docker-compose.test.yml build
      - run:
          name: docker-compose up
          command: docker-compose -f docker-compose.test.yml up -d
      # - run:
      #     name: yarn install
      #     command: docker-compose exec web yarn install
      # - run:
      #     name: install bootstrap
      #     command: |
      #       docker-compose exec web yarn add bootstrap-material-design \
      #         docker-compose exec web yarn install
      - run:
          name: wait for db launch
          command: sleep 10
      - run:
          name: setup db
          command: docker-compose -f docker-compose.test.yml run web rails db:create db:migrate RAILS_ENV=test
      - run:
          name: test
          command: |
            docker-compose -f docker-compose.test.yml exec web bundle exec rspec spec  \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results: #テスト結果のアップロード
          path: test_results
      - store_artifacts:
          path: tmp/screenshots/
      - run:
          name: Rubocop #rubocopの起動
          command: docker-compose -f docker-compose.test.yml exec web bundle exec rubocop --lint
      - run:
          name: docker-compose down
          command: docker-compose down