version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose -f docker-compose.test.yml build
      - run:
          name: docker-compose up
          command: docker-compose -f docker-compose.test.yml up -d
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-
      - run:
          name: yarn install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: install bootstrap material degign
          command: |
            yarn add bootstrap-material-design \
              yarn install
      - run:
          name: wait for db launch
          command: sleep 10
      - run:
          name: setup db
          command: docker-compose -f docker-compose.test.yml run web rails db:create db:migrate RAILS_ENV=test
    #   - run:
    #       name: rerun bundle install
    #       command: docker-compose -f docker-compose.test.yml exec web bundle install
      - run:
          name: test
          command: |
            docker-compose -f docker-compose.test.yml exec web bundle exec rspec spec  \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results: #テスト結果のアップロード
          path: test_results
      - store_artifacts:
          path: tmp/screenshots/
      - run:
          name: Rubocop #rubocopの起動
          command: bundle exec rubocop --lint
      - run:
          name: docker-compose down
          command: docker-compose down