version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: setup database.yml
          command: cp config/database.ci.yml config/database.yml
      - run:
          name: wait for db launch
          command: sleep 10
      - run:
          name: setup db
          command: docker-compose run web rails db:create db:migrate
      - run:
          name: test
          command: |
            docker-compose run web bundle exec rspec spec  \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results: #テスト結果のアップロード
          path: test_results
      - store_artifacts:
          path: tmp/screenshots/
      - run:
          name: Rubocop #rubocopの起動
          command: bundle exec rubocop --lint
      - run:
          name: docker-compose down
          command: docker-compose down