version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose -f docker-compose.test.yml build
      - run:
          name: docker-compose up
          command: docker-compose -f docker-compose.test.yml up -d
      - run:
          name: wait for db launch
          command: sleep 10
      - run:
          name: check some logs
          command: docker-compose logs app
      - run:
          name: setup db
          command: docker-compose -f docker-compose.test.yml run app rails db:create db:migrate RAILS_ENV=test
      - run:
          name: test
          command: |
            docker-compose -f docker-compose.test.yml run app bundle exec rspec spec  \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results: #テスト結果のアップロード
          path: test_results
      - store_artifacts:
          path: tmp/screenshots/
      - run:
          name: Rubocop #rubocopの起動
          command: docker-compose -f docker-compose.test.yml run app bundle exec rubocop --lint
      - run:
          name: docker-compose down
          command: docker-compose down