default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){ 5 } %>
  username: 'root'
  port: 3306
  # password: "6989"
test:
  <<: *default
  database: diary_app_test
  host: test-db #docker-compose.test.ymlのservice名