default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){ 5 } %>
  username: 'root'
  port: 3306
  host: '127.0.0.1'
  database: test-db
  # password: "6989"
test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE", "diary_app_test") %>
  host: <%= ENV.fetch("MYSQL_ROOT_HOST", "%") %>
  # host: test-db #docker-compose.ymlのservice名
  # host: test-db #docker-compose.ymlのservice名