default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){ 5 } %>
  # host: 127.0.0.1
  # ローカルホストではなくコンテナで指定する
  port: 3306
  username: root
  password:
  # database: test-db

test:
  <<: *default
  database: diary_app_test
  host: <%= ENV['DB_HOST'] %>
  # host: test-db #docker-compose.ymlのservice名