default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){ 5 } %>
  # host: 127.0.0.1
  # ローカルホストではなくコンテナで指定する
  port: 3308
  username: root
  password:
  database: test-db

test:
  <<: *default
  database: diary_app_test