default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){ 5 } %>
  host: <%= ENV.fetch("MYSQL_HOST"){ 127.0.0.1 } %>
  port: <%= ENV.fetch("MYSQL_PORT"){ 3306 } %>
  username: root
  password: "6989"

test:
  <<: *default
  database: ci_test