meta:
  site: ダイアリー体験フォーラム
  title: ダイアリー体験フォーラム
  description: 誰もが心の悩みを持つストレス社会・・・"ダイアリー体験フォーラム"で様々なトラブルに向き合う新しいセルフマネージメント！「以前の自分に立ち戻りたい」という方に、確かな自己成長の実感はもちろん、毎日簡単に続けられる機能を実現！
  keywords:
    - 森田療法
    - ダイアリー
    - 日記療法
  og:
    type: website
    image_path: ogp.png
payjp:
# credentialsに設置するとCIビルドでnilエラーになる
  pk: pk_test_bcd88620fea3ca1e2abda930
  sk: sk_test_b9ccaf28227079f60abcea0e
