FROM nginx:1.15.8

# パッケージのインストール
RUN apt-get update && \
    apt-get install -y apt-utils \
    locales && \
    echo "ja_JP.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen ja_JP.UTF-8

# インクルード用のディレクトリ内を削除(https://qiita.com/eighty8/items/0288ab9c127ddb683315)
RUN rm -f /etc/nginx/conf.d/*

# # Nginx設定ファイルコピー,nginx.confがデフォ
ADD nginx.conf /etc/nginx/nginx.conf

# ビルド完了後にNginxを起動
CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf